on:
  push:
    branches: [main]
  workflow_dispatch:
name: Deploy
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v2
    
    - name: Minify JSON
      uses: StefanEnsmann/Minify-JSON-Action@1.0.6
      with:
        input_file: pokedex.json
    
    - name: Minify JSON
      uses: StefanEnsmann/Minify-JSON-Action@1.0.6
      with:
        input_file: types.json

    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        server-dir: ./pkmn_data/
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
